DROP TABLE TBAA_USER;
DROP TABLE TBAA_CTMEMO;
DROP TABLE TBGA_COMMENT;
DROP TABLE TBBA_BOARD_MANAGER;
DROP TABLE TBBB_BOARD_ARTICLE;
DROP TABLE TBYA_ATTACH_FILE;

CREATE TABLE TBAA_USER (
  USER_ID varchar(20) NOT NULL,
  NAME varchar(50) NOT NULL,
  PASSWD varchar(50) NOT NULL,
  EMAIL varchar(100),
	ADMIN_F varchar(1) NOT NULL,	 			  
	DELETE_F varchar(1) NOT NULL,	 			  
  PRIMARY KEY  (USER_ID)
);
INSERT INTO TBAA_USER(USER_ID, NAME, PASSWD, EMAIL, ADMIN_F, DELETE_F) VALUES('setvect', '문학소년', '81dc9bdb52d04dc20036dbd8313ed055', '', 'Y', 'N');

CREATE TABLE TBAB_AUTH (
 	AUTH_SEQ int NOT NULL,
 	NAME varchar(100) NOT NULL,
  URL varchar(200) NOT NULL,
  PARAMETER varchar(100) NOT NULL,
  PRIMARY KEY  (AUTH_SEQ)
);

INSERT INTO TBAB_AUTH(AUTH_SEQ, NAME, URL, PARAMETER) VALUES(10, '복슬노트', '/note/*', '*');


CREATE TABLE TBAC_AUTH_MAP (
 	AUTH_SEQ int NOT NULL,
  USER_ID varchar(20) NOT NULL,
  PRIMARY KEY  (AUTH_SEQ, USER_ID)
);

ALTER TABLE TBAC_AUTH_MAP ADD FOREIGN KEY (AUTH_SEQ) REFERENCES TBAB_AUTH(AUTH_SEQ);
ALTER TABLE TBAC_AUTH_MAP ADD FOREIGN KEY (USER_ID) REFERENCES TBAA_USER(USER_ID);

CREATE TABLE TBCA_CTMEMO  (
	CTMEMO_SEQ int NOT NULL,
	CONTENT varchar(4000) NOT NULL,
	FONT_CSS varchar(20) NOT NULL,
	BG_CSS varchar(20) NOT NULL,
	Z_INDEX int NOT NULL,
	WIDTH int NOT NULL,
	HEIGHT int NOT NULL,
	POSITION_X int NOT NULL,
	POSITION_Y int NOT NULL,
	UPT_DATE datetime NOT NULL,
	REG_DATE datetime NOT NULL,
	DELETE_F varchar(1) NOT NULL,
	PRIMARY KEY  (CTMEMO_SEQ)
);

CREATE TABLE TBGA_COMMENT(
	COMMENT_SEQ		int NOT NULL,
	MODULE_NAME		varchar(20) NOT NULL,
	MODULE_ID			varchar(50) NOT NULL,		
	USER_ID				varchar(20) NOT NULL,
	CONTENT				varchar(4000) NOT NULL,
	REG_DATE			datetime NOT NULL,
  PRIMARY KEY  (COMMENT_SEQ)
);

INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(1,'MAIN', 1, 'setvect', 'comment1', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(2,'MAIN', 2, 'setvect', 'comment2 boksl', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(3,'MAIN', 3, 'setvect', 'comment3', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(4,'MAIN', 4, 'setvect', 'comment4', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(5,'MAIN', 5, 'setvect', 'comment5', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(6,'MAIN', 6, 'setvect', 'comment6', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(7,'MAIN', 7, 'setvect', 'comment7', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(8,'MAIN', 8, 'setvect', 'comment8', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(9,'MAIN', 9, 'setvect', 'comment9', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(10,'MAIN', 10, 'setvect', 'comment10', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(11,'MAIN', 11, 'setvect', 'comment11', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(12,'MAIN', 12, 'setvect', 'comment12', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(13,'MAIN', 13, 'setvect', 'comment13', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(14,'MAIN', 14, 'setvect', 'comment14', now());
INSERT INTO TBGA_COMMENT(COMMENT_SEQ, MODULE_NAME, MODULE_ID, USER_ID, CONTENT, REG_DATE) VALUES(15,'MAIN', 15, 'setvect', 'comment15', now());


CREATE TABLE TBBA_BOARD_MANAGER (
  BOARD_CODE varchar(20) NOT NULL,
  NAME varchar(50) NOT NULL,
  UPLOAD_LIMIT int NOT NULL,
  REPLY_F varchar(1) NOT NULL,
  COMMENT_F varchar(1) NOT NULL,
  ATTACH_F varchar(1) NOT NULL,
  ENCODE_F varchar(1) NOT NULL,
	DELETE_F varchar(1) NOT NULL,	  
  PRIMARY KEY  (BOARD_CODE)
);

INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA01', 'notice', 5000, 'N', 'N', 'Y', 'N', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA02', 'literature', 5000, 'N', 'N', 'Y', 'Y', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA03', 'notice 3', 5000, 'N', 'N', 'Y', 'N', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA04', 'notice 4', 5000, 'N', 'N', 'Y', 'Y', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA05', 'notice 5', 5000, 'N', 'N', 'Y', 'N', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA06', 'notice 6', 5000, 'N', 'N', 'Y', 'Y', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA07', 'notice 7', 5000, 'N', 'N', 'Y', 'N', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA08', 'notice 8', 5000, 'N', 'N', 'Y', 'Y', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA09', 'notice 9', 5000, 'N', 'N', 'Y', 'N', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA10', 'notice 10', 5000, 'N', 'N', 'Y', 'Y', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA11', 'notice 11', 5000, 'N', 'N', 'Y', 'N', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA12', 'notice 12', 5000, 'N', 'N', 'Y', 'Y', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA13', 'notice 13', 5000, 'N', 'N', 'Y', 'N', 'N');
INSERT INTO TBBA_BOARD_MANAGER(BOARD_CODE,NAME,UPLOAD_LIMIT,REPLY_F,COMMENT_F,ATTACH_F,ENCODE_F,DELETE_F) VALUES('BDAAAA14', 'notice 14', 5000, 'N', 'N', 'Y', 'Y', 'N');

CREATE TABLE TBBB_BOARD_ARTICLE (
  ARTICLE_SEQ int NOT NULL,
  BOARD_CODE varchar(20) NOT NULL,
  USER_ID varchar(20),
  IDX1 int NOT NULL,
  IDX2 int NOT NULL,
  IDX3 int NOT NULL,
  DEPTH_LEVEL int NOT NULL,
  TITLE varchar(200) NOT NULL,
  NAME varchar(50) NOT NULL,
  EMAIL varchar(100),
  PASSWD varchar(10),
  CONTENT text NOT NULL,
  IP varchar(20) NOT NULL,
  HIT_COUNT int NOT NULL,
  ENCODE_F varchar(1) NOT NULL,
  REG_DATE datetime NOT NULL,
	DELETE_F varchar(1) NOT NULL,	 			  
  PRIMARY KEY  (ARTICLE_SEQ)
);

ALTER TABLE TBBB_BOARD_ARTICLE	ADD FOREIGN KEY (BOARD_CODE) REFERENCES TBBA_BOARD_MANAGER(BOARD_CODE);

INSERT INTO TBBB_BOARD_ARTICLE(ARTICLE_SEQ,BOARD_CODE,USER_ID,IDX1,IDX2,IDX3,DEPTH_LEVEL,TITLE,NAME,EMAIL,PASSWD,CONTENT,IP,HIT_COUNT,ENCODE_F,REG_DATE,DELETE_F) 
VALUES(1, 'BDAAAA01', '', 1,1,1,1,'제목1(파일)', '이름1', 'a@a.com','','내용1','127.0.0.1',0,'N',now(),'N');

INSERT INTO TBBB_BOARD_ARTICLE(ARTICLE_SEQ,BOARD_CODE,USER_ID,IDX1,IDX2,IDX3,DEPTH_LEVEL,TITLE,NAME,EMAIL,PASSWD,CONTENT,IP,HIT_COUNT,ENCODE_F,REG_DATE,DELETE_F) 
VALUES(2, 'BDAAAA01', '', 2,1,1,1,'제목2(이미지)', '이름2', 'a@a.com','','내용2','127.0.0.1',0,'N',now(),'N');

INSERT INTO TBBB_BOARD_ARTICLE(ARTICLE_SEQ,BOARD_CODE,USER_ID,IDX1,IDX2,IDX3,DEPTH_LEVEL,TITLE,NAME,EMAIL,PASSWD,CONTENT,IP,HIT_COUNT,ENCODE_F,REG_DATE,DELETE_F) 
VALUES(3, 'BDAAAA01', '', 3,1,1,1,'제목3', '이름3', 'a@a.com','','내용3','127.0.0.1',0,'N',now(),'N');

CREATE TABLE TBYA_ATTACH_FILE(
	ATTACH_FIlE_SEQ		int NOT NULL,
	MODULE_NAME				varchar(20) NOT NULL,
	MODULE_ID					varchar(50) NOT NULL,
	USER_ID 					varchar(20),
	ORIGINAL_NAME			varchar(250) NOT NULL,
	SAVE_NAME					varchar(250) NOT NULL,
	SIZE							int NOT NULL,
	REG_DATE 					datetime NOT NULL,
  PRIMARY KEY  (ATTACH_FIlE_SEQ)
);

INSERT INTO TBYA_ATTACH_FILE(ATTACH_FIlE_SEQ, MODULE_NAME, MODULE_ID, USER_ID, ORIGINAL_NAME, SAVE_NAME, SIZE, REG_DATE)
VALUES(1, 'BOARD',1, 'setvect', '2.t23.lob.db', '/2015/06/07/file5913327897087789911BOARD_4.db', 4880, now());
INSERT INTO TBYA_ATTACH_FILE(ATTACH_FIlE_SEQ, MODULE_NAME, MODULE_ID, USER_ID, ORIGINAL_NAME, SAVE_NAME, SIZE, REG_DATE)
VALUES(2, 'BOARD',1, 'setvect', '5.t23.lob.db', '/2015/06/07/file619837131936392773BOARD_4.db', 7776, now());

INSERT INTO TBYA_ATTACH_FILE(ATTACH_FIlE_SEQ, MODULE_NAME, MODULE_ID, USER_ID, ORIGINAL_NAME, SAVE_NAME, SIZE, REG_DATE)
VALUES(3, 'BOARD',2, 'setvect', '1.jpg', '/2015/06/07/a.jpg', 112984, now());
INSERT INTO TBYA_ATTACH_FILE(ATTACH_FIlE_SEQ, MODULE_NAME, MODULE_ID, USER_ID, ORIGINAL_NAME, SAVE_NAME, SIZE, REG_DATE)
VALUES(4, 'BOARD',2, 'setvect', '2.jpg', '/2015/06/07/b.jpg', 201617, now());


CREATE TABLE TBDA_NOTE_CATEGORY (
  CATEGORY_SEQ int NOT NULL,
  NAME varchar(50) NOT NULL,
  REG_DATE datetime NOT NULL,
	DELETE_F varchar(1) NOT NULL,
  PRIMARY KEY  (CATEGORY_SEQ)
);


CREATE TABLE TBDB_NOTE (
	NOTE_SEQ		int NOT NULL,
  CATEGORY_SEQ int NOT NULL,
  TITLE varchar(200) NOT NULL,
  CONTENT text NOT NULL,
	UPT_DATE datetime NOT NULL,
	REG_DATE datetime NOT NULL,
	DELETE_F varchar(1) NOT NULL,
  PRIMARY KEY  (NOTE_SEQ)
);

ALTER TABLE TBDB_NOTE	ADD FOREIGN KEY (CATEGORY_SEQ) REFERENCES TBDA_NOTE_CATEGORY(CATEGORY_SEQ);

